### ISSUE TITLE
Frequent restart required

### ISSUE THREAD

**Issue by Tobias1122334** [planbnet/livisi_unofficial#130]
## System Information

version | core-2024.6.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 6.6.28-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1393
Downloaded Repositories | 19
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 4. April 2025 um 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | false
remote_server | eu-central-1-0.ui.nabu.casa
certificate_status | ready
instance_id | c926ddd70c444db29d2122b4feed732f
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.3
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.0
agent_version | 1.6.0
docker_version | 25.0.5
disk_total | 57.8 GB
disk_used | 28.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.15.0), File editor (5.8.0), Terminal & SSH (9.14.0), Mosquitto broker (6.4.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 15
-- | --
resources | 5
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 13. Juni 2024 um 22:15
-- | --
current_recorder_run | 16. Juni 2024 um 13:49
estimated_db_size | 1602.60 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Since about two weeks I need to regularly reload the integration as devices/ entities are not reachable in Home Assistant anymore. Usually a daily reload is required. After reloading the integration all devices/ entities are available again.
Other users at Facebook report similar issues.

### Reproduction steps

The entities automatically lose connection/ are not reachable in Home Assistant anymore usually daily.

### Debug logs

```text
Debug logging has just been activated
```

**Comment by planbnet** [comment]
Ohne weitere Infos oder Debug logs kann ich da leider nichts zu sagen... Ich hab keinerlei Probleme und ich wüsste auch nicht, was sich in den letzten zwei Wochen verändert haben sollte.

**Comment by Tobias1122334** [comment]
Hallo,

 

ich habe den Debugmodus aktiviert. Gibt es irgendwo eine Anleitung wie ich die Debug logs herunterladen kann?

Ich habe erstmal übergangsweise eine Automatik erstellt, die die Integration ein mal am Tag neu lädt.

 

Von: Felix Rotthowe ***@***.***> 
Gesendet: Freitag, 21. Juni 2024 13:09
An: planbnet/livisi_unofficial ***@***.***>
Cc: Tobias1122334 ***@***.***>; Author ***@***.***>
Betreff: Re: [planbnet/livisi_unofficial] Frequent restart required (Issue #130)

 

Ohne weitere Infos oder Debug logs kann ich da leider nichts zu sagen... Ich hab keinerlei Probleme und ich wüsste auch nicht, was sich in den letzten zwei Wochen verändert haben sollte.

**Comment by planbnet** [comment]
Auf der Seite der Integration erscheint dann doch der Button "Debug Logs laden" oder so.. Wichtig ist nur, dass der Fehler auch in den Logs enthalten ist, er muss also aufgetreten sein.

**Comment by Tobias1122334** [comment]
Ok, anbei der Debug Log. Der Fehler sollte in dem Zeitpunkt aufgetreten sein.

[home-assistant_livisi_2024-06-21T11-46-33.602Z.zip](https://github.com/user-attachments/files/15927089/home-assistant_livisi_2024-06-21T11-46-33.602Z.zip)

**Comment by planbnet** [comment]
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://192.168.178.74:8080/capability//state')

There seems to be a missing capability id. unfortunately the stack trace is incomplete here...

**Comment by Tobias1122334** [comment]
Ok, thanks. But can you tell me what that exactly means?

**Comment by planbnet** [comment]
No because I don't know :)
But maybe the next version fixes it...

**Comment by planbnet** [comment]
Please try 1.11.2 (you need to set hacs to download beta versions)

**Comment by JackSmart007** [comment]
Same issue here and getting worse since the devices won’t reconnect to HA after restarting the integration and/or HomeAssistant.

**Comment by planbnet** [comment]
Can you provide a log with the error created with the latest version. This seems to be a problem with the v1 SHC and I don’t have one so I cannot reproduce this.

**Comment by JackSmart007** [comment]
Logger: homeassistant.components.cover
Quelle: helpers/entity_platform.py:875
Integration: Abdeckung (Dokumentation, Probleme)
Erstmals aufgetreten: 17:58:19 (5 Vorkommnisse)
Zuletzt protokolliert: 17:58:23

Entity id already exists - ignoring: cover.balkon
Entity id already exists - ignoring: cover.rollo_garage
Entity id already exists - ignoring: cover.untergeschoss_links
Entity id already exists - ignoring: cover.untergeschoss_rechts
Entity id already exists - ignoring: cover.rollo_gastebad

**Comment by JackSmart007** [comment]
Funfact: The buttons of the devices are supporting their „pressed“ state when they are pressed but the devices themselves remain unavailable.

**Comment by Tobias1122334** [comment]
> Can you provide a log with the error created with the latest version. This seems to be a problem with the v1 SHC and I don’t have one so I cannot reproduce this.

If you mean that this is linked to the 1st generation of the SHC ("Zentrale") I can say that at my side the issue appears with the second generation.

**Comment by Navidar** [comment]
> Can you provide a log with the error created with the latest version. This seems to be a problem with the v1 SHC and I don’t have one so I cannot reproduce this.

I have this issue with SHC 2.0. Several times during the day I have to restart the integration.

**Comment by Koerner** [comment]
I encounter the problem with v1 SHC

**Comment by Gerrett84** [comment]
The problem now also occurs with me (SHC2)

**Comment by Uli112Winsen** [comment]
The problem now also occurs with me (SHC2)

**Comment by sidfame** [comment]
Same here with SHC 2.0. Daily restarts required.

**Comment by planbnet** [comment]
I would really like to fix this bug, but my installation is running stable for weeks or months without restart, so something that is not happening in my setup must be causing this. Without any additional information i am unfortunately unable to help. 
The bug seems to be happening on reauthentication (the SHC token becomes invalid after 24 hours) - but normally a new token is requested and used from then on. I guess there must be a special case where reauth fails (permanently) so a restart is required, but that’s all I can say without the log messages at that time

**Comment by Dirki200** [comment]
Hi! Same issue here, I have the SHC 2.0

**Comment by Navidar** [comment]
> I would really like to fix this bug, but my installation is running stable for weeks or months without restart, so something that is not happening in my setup must be causing this. Without any additional information i am unfortunately unable to help. The bug seems to be happening on reauthentication (the SHC token becomes invalid after 24 hours) - but normally a new token is requested and used from then on. I guess there must be a special case where reauth fails (permanently) so a restart is required, but that’s all I can say without the log messages at that time

Of we knew which logs, where to activate and which part of hte logs shall we deliver, we may deliver the right logs for analysis. The problems on my server continue every day, sometimes several times per day. :)

**Comment by thas1x** [comment]
Having the same issue and fix.
Here is my automation to restart when one randomly chosen Livisi device of mine becomes unavailable:
`- id: 1234
  alias: Restart Home Assistant if Livisi unavailable
  description: Restart the home assistant operating system if Livisi device becomes unavailable
  triggers:
  - trigger: state
    entity_id:
    - xzy
    to: unavailable
    for:
      hours: 0
      minutes: 0
      seconds: 10
  - trigger: state
    entity_id:
    - xyz
    to: unknown
    for:
      hours: 0
      minutes: 0
      seconds: 10
  actions:
  - action: homeassistant.restart
    data: {}`

**Comment by Gerrett84** [comment]
> Having the same issue and fix.
> 
> Here is my automation to restart when one randomly chosen Livisi device of mine becomes unavailable:
> 
> `- id: 1234
> 
>   alias: Restart Home Assistant if Livisi unavailable
> 
>   description: Restart the home assistant operating system if Livisi device becomes unavailable
> 
>   triggers:
> 
>   - trigger: state
> 
>     entity_id:
> 
>     - xzy
> 
>     to: unavailable
> 
>     for:
> 
>       hours: 0
> 
>       minutes: 0
> 
>       seconds: 10
> 
>   - trigger: state
> 
>     entity_id:
> 
>     - xyz
> 
>     to: unknown
> 
>     for:
> 
>       hours: 0
> 
>       minutes: 0
> 
>       seconds: 10
> 
>   actions:
> 
>   - action: homeassistant.restart
> 
>     data: {}`

It should be sufficient to reload the livisi with: 
 - action: homeassistant.reload_config_entry

**Comment by thas1x** [comment]
> > Having the same issue and fix.
> > Here is my automation to restart when one randomly chosen Livisi device of mine becomes unavailable:
> > `- id: 1234
> > alias: Restart Home Assistant if Livisi unavailable
> > description: Restart the home assistant operating system if Livisi device becomes unavailable
> > triggers:
> > 
> > * trigger: state
> >   entity_id:
> >   
> >   * xzy
> >   
> >   to: unavailable
> >   for:
> >   hours: 0
> >   minutes: 0
> >   seconds: 10
> > * trigger: state
> >   entity_id:
> >   
> >   * xyz
> >   
> >   to: unknown
> >   for:
> >   hours: 0
> >   minutes: 0
> >   seconds: 10
> > 
> > actions:
> > 
> > * action: homeassistant.restart
> >   data: {}`
> 
> It should be sufficient to reload the livisi integration with:
> 
> * action: homeassistant.reload_config_entry

It is not sufficient to just reload on my side. So for me the workaround only works with "homeassistant.restart".

**Comment by thas1x** [comment]
> I would really like to fix this bug, but my installation is running stable for weeks or months without restart, so something that is not happening in my setup must be causing this. Without any additional information i am unfortunately unable to help.
> The bug seems to be happening on reauthentication (the SHC token becomes invalid after 24 hours) - but normally a new token is requested and used from then on. I guess there must be a special case where reauth fails (permanently) so a restart is required, but that’s all I can say without the log messages at that time

Here are the debug logs (removed IPs, ports and keys and had to change from .rtf to .txt to be able to upload it). Very much appreciate your support!
[20241021_Logs_Livisi_Error.txt](https://github.com/user-attachments/files/17474916/20241021_Logs_Livisi_Error.txt)

**Comment by planbnet** [comment]
> Here are the debug logs (removed IPs, ports and keys and had to change from .rtf to .txt to be able to upload it). Very much appreciate your support! [20241021_Logs_Livisi_Error.txt](https://github.com/user-attachments/files/17474916/20241021_Logs_Livisi_Error.txt)

Thanks. Now this seems to be something completely different than in the other logs so far, but maybe the cause for all the random errors people report: Your network goes down and the integration does not correctly recover from it even when it reports success (in the last 3 lines of the log). Seems plausible that people with unstable networks are affected by this. I'll try pull the LAN plug of the SHC and see what happens...

**Comment by JackSmart007** [comment]
Both HomeAssistant and Livisi SHC are connected via LAN, so no unstable Network Environment here.

**Comment by macindoc** [comment]
Thanks for reviewing this issue. To potentially improve stability, adding a retry mechanism for the WebSocket connection might help in cases where temporary network issues cause these CancelledError and TimeoutError messages.

It looks like the listen_for_events method in custom_components/livisi/livisi_connector.py connects to the WebSocket without retry logic. Would it be possible to implement a retry mechanism within this method?

**Comment by planbnet** [comment]
Not retying on first connect isn't the problem here, as the problems only appear after hours. But the existing retry logic on disconnected websocket connections might actually be the problem, as it recurses in a possibly infinite async-await chain (because reestablishing the connection is don from the on_close handler).
I fixed this in commit 2f93b45b4f9c16effb617270f93619a23e0163d6 - can anyone try if this resolves the problem?

**Comment by macindoc** [comment]
Thanks for the quick response and for implementing this change! I’ll apply the update and monitor the connection stability over time. I’ll let you know if the issue persists.

**Comment by macindoc** [comment]
Thanks for the recent update! Unfortunately, the WebSocket connection issue persists, though the error behavior has changed.

After a few hours, I now see repeated TimeoutError and CancelledError messages in the log. It seems that the on_websocket_close function continues to enter a loop where reconnect_error is repeatedly raised. This might suggest that the reconnection attempt still fails to establish a stable connection and is being repeatedly triggered.

The error trace indicates that TimeoutError occurs when trying to re-establish the connection, possibly due to a network or API response issue. This might be creating a feedback loop where on_websocket_close keeps trying to reconnect, but the connection doesn’t succeed.

Would it be possible to add a conditional check or limit the number of reconnection attempts to prevent this loop from continuing indefinitely? I’d be happy to test any further updates.

Thank you for your support!
[home-assistant_livisi_2024-11-12T07-34-59.221Z.log.txt](https://github.com/user-attachments/files/17712854/home-assistant_livisi_2024-11-12T07-34-59.221Z.log.txt)

**Comment by macindoc** [comment]
Hi Felix,

Thank you for the recent updates. I’ve applied the latest version, and as requested, here’s the new log file after the changes.

[home-assistant_livisi_2024-11-13T20-03-40.153Z.log.txt](https://github.com/user-attachments/files/17738767/home-assistant_livisi_2024-11-13T20-03-40.153Z.log.txt)

Unfortunately, the WebSocket connection issue persists, and I’m still seeing repeated TimeoutError and CancelledError messages. While the exponential backoff and additional logging are helpful, the connection continues to drop after some time and doesn’t fully recover.

Let me know if there’s anything else I can test, or if any other modifications could help stabilize the connection. I’ll be happy to provide more details if needed.

Thank you again for your support!

**Comment by planbnet** [comment]
> Thank you for the recent updates. I’ve applied the latest version, and as requested, here’s the new log file after the changes.

Are you sure you applied the changes? This is not the current line 160 in coordinator.py:
"/config/custom_components/livisi/coordinator.py", line 160, in on_websocket_close
    raise reconnect_error

**Comment by macindoc** [comment]
Hi Felix,

First of all, thank you for the recent code adjustments. Since implementing the updates, I haven’t encountered any error messages, which is great!

However, a new issue has appeared: after some time, the status of devices is no longer updating. For example, the shutters still appear as open in Home Assistant, even though they’ve been closed for a while. It seems that the integration may not be receiving or processing state updates consistently.

Could you advise on what to check next or suggest any adjustments that might help resolve this new problem?

Thank you again for your continued support!

**Comment by zerocool1122** [comment]
My Livisi logs out every day now, and the thermostats are always unreachable. I have to unplug the bridge from power and restart Home Assistant every time to make it work again.

Is there a solution for this now?

**Comment by planbnet** [comment]
This issue seems to have become a bit of a catch-all for all connection related problems. Please, everyone reporting here, be sure to narrow down your problem first. 

> My Livisi logs out every day now, and the thermostats are always unreachable. I have to unplug the bridge from power and restart Home Assistant every time to make it work again.

If you have to unplug the bridge from power (and a restart of home assistant is not enough), this is not a problem of this integration. It means that the bridge somehow locks up.

**Comment by macindoc** [comment]
> So, just to clarify: the websocket connection is not closed anymore (and thus devices are not switched to unreachable state), but changes aren't processed?

Correct. 

1. Devices are always visible, no disconnections.
2. HA -->Devices: devices will react to changes performed in HA (even in case of 3.)
3. Devices-->HA: device status is not updated in HA after some hours

> We need to find the root cause for this. It's okay for the web socket connections to be closed after being idle for some time, as it needs to be reastabilshed on failure anyways. Polling is a fallback that might work (the implementation is already polling for device availablility and all the other data), but does not provide instant updates (e.g. when a light is switched on).

My assumption is that status messages are received in HA, but not processed in HA after some time. Let me know how I can help with finding the root cause.

**Comment by planbnet** [comment]
Then my best guess is that some message comes in that is not correctly handled (which is never sent in my setup) and the exception from that error is somehow lost inside the caller chain and never handled (though simply ignoring all subsequent messages)

Maybe add a `try / except` around all the code of `consumer_handler` in `livisi_websocket.py` and ERROR-log it...?

**Comment by macindoc** [comment]
**Good news!**

Feedback on Livisi Integration Testing after applying your suggested adaptations:

Overall Observations:

The integration has been running successfully for 15+ hours. Device control from HA to devices works flawlessly, and the WebSocket connection remains operational.
The issue of device-to-HA state updates stopping after extended runtime has not reoccurred during this test phase.
Log Findings:

Warnings:
Several instances of "Received event with no properties, skipping."
Example timestamp: 2024-11-22 09:27:36.
These events appear to have incomplete or malformed data, and the integration handles them gracefully by skipping.

Errors:
WebSocket Consumer Handler Errors:
Frequent disconnections with traceback indicating websockets.exceptions.ConnectionClosedError: sent 1011 (internal error) keepalive ping timeout; no close frame received.
Despite these, the integration successfully re-establishes the WebSocket connection shortly after each disconnection.
Example timestamps:
Error: 2024-11-21 22:47:43.
Reconnection: 2024-11-21 22:47:43.

Stability:
The fallback mechanism for handling WebSocket disconnections is working well.
The additional logging improvements allow better traceability of WebSocket issues and events.

I've attached a trimmed-down log file for your reference, highlighting the warnings and errors mentioned above. Please let me know if you'd like me to test additional scenarios or configurations.

[home-assistant.short.log.txt](https://github.com/user-attachments/files/17869600/home-assistant.short.log.txt)

**Comment by planbnet** [comment]
I've created a new pre-release which hopefully fixes this issue, thanks @macindoc for helping me debug this!

**Comment by planbnet** [comment]
I'm not sure why, as the error in your log is a CancelledError, which is the one I am handling. The only other difference seems to be the `while not _disconnecting` line. Whatever, I now simply took your code from the gist. Please check if it still works for you so we can *finally* close this issue 😵‍💫

**Comment by Navidar** [comment]
I am following the discussion, thanks to @planbnet and @macindoc. 

I'd just like to reassure that we are still talking about the initial issue: 

1) This issue occurs only with livisi_unofficial integration, correct?  Are we talking about the same thing?

2) Could anyone please describe to a non-github how to implement the change? I am just a user of HAOS+livisi_unofficial. Shall we wait unil a new release comes or can we implement the code proposed here? If the latter, could you please explain where to go and change in which file, starting in Terminal from /config, please?

Thanks again!

**Comment by thas1x** [comment]
Hi all,some additional info that might explain what Sinan G. is experiencing:I have found that on SHC 1 the RAM fills up over a few days.It starts at around 50% after a restart.When it goes above approx. 90% the first entities become unavailable.At some point around 95-100% RAM nothing is working anymore and SHC itself becomes unavailable.A restart (unplug power, then when running restart HA) helps in that case.Thank you and best regards!Am 25.11.2024 um 09:51 schrieb Sinan G. ***@***.***>:﻿
Hi Felix,
I’ve conducted extensive testing with the latest version and wanted to share my observations and findings to help identify and address the issues I encountered. Here’s a detailed summary:
Test Context
The test was conducted over approximately 50 hours of integration runtime.
Initially:
Device control from Home Assistant (HA) to Livisi devices worked flawlessly.
The WebSocket connection remained stable, and device status updates were accurately reflected in HA.
However, towards the end:
Device statuses stopped updating in HA, even though device control functionality from HA continued to work as expected.
High-Level Statistics and Observations
WebSocket Errors:
A total of 153 errors involving WebSocket disconnections (e.g., Keepalive Ping Timeout, HTTP 401) occurred during the runtime.
Despite frequent reconnections, device status updates gradually stopped flowing into HA.
Malformed Events:
22 warnings of the type Received event with no properties, skipping were observed.
These events were skipped without affecting overall stability.
Token Handling:
Early token expiration occurred but was recovered successfully.
Later in the runtime, persistent HTTP 401 errors appeared, potentially related to token handling during reconnections.
Patterns Observed in the Logs
WebSocket Disconnections:
Frequent Keepalive Ping Timeout errors, followed by successful reconnections.
Over time, these errors coincided with the loss of device status updates in HA.
Malformed Events:
Warnings such as Received event with no properties became more frequent later in the log (e.g., after 2024-11-23 08:01:05).
These may indicate anomalies in the events being sent by Livisi.
Token Expiration:
Early token expiration was handled successfully.
Persistent HTTP 401 errors appeared in the latter part of the runtime.
Control vs. Status Updates:
Device control remained reliable throughout, but status updates stopped, likely due to event-processing issues or event loss.
log_short_202411241750.txt
If helpful, I can enable verbose logging to capture detailed WebSocket communication and event payloads for further analysis. Please let me know if there are specific scenarios or configurations you’d like me to test further.
Thanks for your efforts on this integration!

**Comment by Navidar** [comment]
I installed after the disvussion here the last version 1.11.1. Interestingsly, the issue with unavailable components disappeared. It's been now around four days that I didn't need to reload the integration. But what I am observing another issue. The stati of the livisi components do not update on home assistant, althought the initiated action gets performed. 

Example: On the home assistant page I change the temperature from 22 to 15 degrees. Ones i reload the page, hoem assistant still shows 22 degrees. But the command is executed correctly. On Livisi page the temperature of the particular thermostat shows 15 degres.

**Comment by macindoc** [comment]
I wanted to provide an update after further testing. I have found that removing the Philips Hue driver from the Livisi SHC (Smart Home Controller) has resolved the issue for me entirely. Since making this change, the integration has been running smoothly without any significant interruptions.

Through extensive logging, I’ve observed that occasional WebSocket connection issues still occur, but they are now being gracefully handled by the code I provided. The reconnections are stable, and the integration continues to function as expected.

As far as I’m concerned, this issue can be considered resolved.

**@planbnet** : I would recommend promoting version 1.11.3 (pre-release) to 1.11.3 (final).

Thanks again for your support and collaboration!

**Comment by Uli112Winsen** [comment]
Wow, thank you to everyone involved for troubleshooting and finding a solution! I also had total crashes every few hours. I simply uninstalled the Medion driver. My SHC 2 now only has the innogy driver in version 1.0.164.0. HACS Livisi Unofficial Fork Version 1.12.0. No more crashes since then! Thank you very much for your help!
